# Generated by Django 3.0.6 on 2020-05-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='addon_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='combo_item',
            field=models.ManyToManyField(blank=True, to='carts.ComboCartItem'),
        ),
    ]
