# Generated by Django 3.0.6 on 2020-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200522_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='addoncartitem',
            name='addon_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
