# Generated by Django 3.0.6 on 2020-05-20 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0002_auto_20200520_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Combo'),
        ),
    ]
