# Generated by Django 3.0.6 on 2020-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_addoncartitem_addon_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='addon_item',
            field=models.ManyToManyField(blank=True, null=True, to='carts.AddonCartItem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='combo_item',
            field=models.ManyToManyField(blank=True, null=True, to='carts.ComboCartItem'),
        ),
    ]
