# Generated by Django 3.0.6 on 2020-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200522_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoncartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='combocartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
