# Generated by Django 3.0.6 on 2020-05-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('carts', '0004_auto_20200522_1943'),
        ('deliverypoints', '0004_selectdeliverypoint_billing_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5.99, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Refunded', 'Refunded')], default='created', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverypoints.SelectDeliveryPoint')),
            ],
        ),
    ]
