# Generated by Django 3.0.6 on 2020-05-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypoints', '0004_selectdeliverypoint_billing_profile'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverypoints.SelectDeliveryPoint'),
        ),
    ]
