# Generated by Django 3.0.6 on 2020-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200525_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('PREPAID', 'PREPAID')], default='created', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Shipped', 'Shipped'), ('Refunded', 'Refunded')], default='created', max_length=120),
        ),
    ]
