# Generated by Django 3.0.6 on 2020-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200525_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('PREPAID', 'PREPAID')], max_length=120),
        ),
    ]
