# Generated by Django 3.0.6 on 2020-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
