# Generated by Django 3.0.6 on 2020-06-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketing_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketing',
            old_name='update',
            new_name='updated',
        ),
    ]
