# Generated by Django 3.0.6 on 2020-05-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='name',
            new_name='title',
        ),
    ]
