# Generated by Django 3.0.6 on 2020-05-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200530_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='title',
            new_name='name',
        ),
    ]
