# Generated by Django 3.0.6 on 2020-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
