# Generated by Django 3.0.6 on 2020-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_combo_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='combo_price',
            new_name='combo_regular_price',
        ),
        migrations.RenameField(
            model_name='prodcut',
            old_name='price',
            new_name='regular_price',
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prodcut',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
