# Generated by Django 3.0.6 on 2020-05-24 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliverypoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectDeliveryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_point', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='deliverypoints.DeliveryPoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
