# Generated by Django 3.0.6 on 2020-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypoints', '0002_selectdeliverypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoint',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
