# Generated by Django 3.0.6 on 2020-05-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypoints', '0004_selectdeliverypoint_billing_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectdeliverypoint',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverypoints.DeliveryPoint'),
        ),
    ]
