# Generated by Django 3.0.7 on 2020-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activeasdasda',
            field=models.BooleanField(default=True),
        ),
    ]
